model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4.1-mini-batch
    litellm_params:
      model: azure/gpt-4.1-mini-batch
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

general_settings:
  master_key: sk-1234
  proxy_batch_polling_interval: 10
  passthrough_managed_object_ids: true